---
title: "Freq_approaches"
author: "Wendel Raymond"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Frequentist approaches to SAV analysis
Use frequentist statistics to compare SAV data and calculate sample size

```{r}
library(tidyverse)
library(pwr)
library(emmeans)
```

### Data

```{r}
set.seed(123)

# Define sample sizes for pre and post-treatment groups
N_proj <- 48
N_ref <- 50

# means
proj_pre_mean <- 30.2
proj_1_mean <- 29.2
proj_3_mean <- 22.9 
proj_5_mean <- 20.8

ref_pre_mean <- 32.5
ref_1_mean <- 30.2
ref_3_mean <- 27.4
ref_5_mean <- 21.3

# sd
proj_pre_sd <- 9.39
proj_1_sd <- 8.38
proj_3_sd <- 8.48 
proj_5_sd <- 7.54

ref_pre_sd <- 10.0
ref_1_sd <- 9.39
ref_3_sd <- 8.75
ref_5_sd <- 7.98

# generate data
proj.pre.dat <- rnorm(N_proj, mean = proj_pre_mean, sd = proj_pre_sd)
proj.1.dat <- rnorm(N_proj, mean = proj_1_mean, sd = proj_1_sd)
proj.3.dat <- rnorm(N_proj, mean = proj_3_mean, sd = proj_3_sd)
proj.5.dat <- rnorm(N_proj, mean = proj_5_mean, sd = proj_5_sd)

ref.pre.dat <- rnorm(N_ref, mean = ref_pre_mean, sd = ref_pre_sd)
ref.1.dat <- rnorm(N_ref, mean = ref_1_mean, sd = ref_1_sd)
ref.3.dat <- rnorm(N_ref, mean = ref_3_mean, sd = ref_3_sd)
ref.5.dat <- rnorm(N_ref, mean = ref_5_mean, sd = ref_5_sd)

# Create a data frame
dat.sim <- data.frame(
  time = c(rep("pre", N_proj), rep("one", N_proj), rep("three", N_proj), rep("five", N_proj), rep("pre", N_ref), rep("one", N_ref), rep("three", N_ref), rep("five", N_ref)),
  site = c(rep("proj", N_proj * 4), rep("ref", N_ref * 4)),
  density = c(proj.pre.dat, proj.1.dat, proj.3.dat, proj.5.dat, ref.pre.dat, ref.1.dat, ref.3.dat, ref.5.dat)
)

dat.sim$time <- factor(dat.sim$time, levels = c("pre", "one", "three", "five"))
dat.sim$site <- factor(dat.sim$site, levels = c("proj", "ref"))

ggplot(dat.sim) +
  geom_histogram(aes(density), binwidth = 1) +
  facet_wrap(~site + time, nrow = 4, ncol = 2)

dat.sim.sum <- dat.sim %>% 
  group_by(time, site) %>% 
  summarise(mean = mean(density),
            sd = sd(density))

dat.sim.sum$time <- factor(dat.sim.sum$time, levels = c("pre", "one", "three", "five"))
dat.sim.sum$site <- factor(dat.sim.sum$site, levels = c("proj", "ref"))

pal <- c("#6A8026", "#3542A1")


ggplot(dat.sim.sum %>% 
         filter(site == "proj")) +
  geom_col(aes(x = time, y = mean, fill = site)) +
  geom_errorbar(aes(x = time, ymin = mean - sd, ymax = mean + sd, group = site), width = 0) +
  scale_fill_manual(values = pal, name = "Site", breaks = c("proj", "ref"), labels = c("Project", "Reference")) +
  geom_hline(aes(yintercept = 30.4), color = pal[1], linetype = "dashed") +
  xlab("Time") +
  ylab("Shoot density (m-sq) +/- SD") +
  theme(text = element_text(size = 12))

ggplot(dat.sim.sum) +
  geom_col(aes(x = time, y = mean, group = site, fill = site), position = position_dodge(1)) +
  geom_errorbar(aes(x = time, ymin = mean - sd, ymax = mean + sd, group = site), position = position_dodge(1), width = 0) +
  scale_fill_manual(values = pal, name = "Site", breaks = c("proj", "ref"), labels = c("Project", "Reference")) +
  geom_hline(aes(yintercept = 30.4), color = pal[1], linetype = "dashed") +
  geom_hline(aes(yintercept = 31.8), color = pal[2], linetype = "dashed") +
  xlab("Time") +
  ylab("Shoot density (m-sq) +/- SD") +
  theme(text = element_text(size = 12))
```

### Compare no refernce 
```{r}
dat.sim.proj <- dat.sim %>% 
  filter(site == "proj")

dat.sim.proj %>% 
  group_by(time) %>% 
  summarize(mean = mean(density),
            sd = sd(density))

mod1 <- glm(density ~ site, data = dat.sim, family = Gamma(link = "log"))

summary(mod1)
anova(mod1)

emmeans(mod1, specs = "time")
```

### Compare with refernece
```{r}
dat.1 <- dat.sim %>% 
  filter(time %in% c("pre", "one")) %>% 
  filter(site %in% c("proj", "ref"))

mod2 <- glm(density ~ time / site, data = dat.1, family = Gamma(link = "log"))

summary(mod2)

dat.3 <- dat.sim %>% 
  filter(time %in% c("pre", "three")) %>% 
  filter(site %in% c("proj", "ref"))

mod3 <- glm(density ~ time / site, data = dat.3, family = Gamma(link = "log"))

summary(mod3)


```


### N star
```{r}
# Known parameters
mean_pre <- 30
alpha <- 0.1      # Significance level
beta <- 0.9       # Desired power
sd_pre <- 10
delta <- (0.2 * mean_pre)  # Minimum detectable effect size (20% change)

# Calculate critical values
z_alpha_over_2 <- qnorm(1 - alpha/2)
z_beta <- abs(qnorm(1 - beta))

# Calculate sample size per group
sample_size <- ((2 * (z_alpha_over_2 + z_beta)^2 * sd_pre^2) / delta^2)
```

```{r}
dat.test <- data.frame(
  dist = c(46, 38, 34, 37, 60, 64, 59)
)

dat.test$prop <- dat.test$dist / sum(dat.test$dist)

dat.test$quad <- round(dat.test$prop * 48, 0)
```

